name = "Beyond the Singularity"
author = "ZotyDev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fcd5686c548daa781b7ad772f55d6627d374059367e105ac5c6347c93d72e77"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
