name = "Beyond the Singularity"
author = "ZotyDev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09c483c961badc5bd85a1b92e93fafa84200f762fce45a7bd542ca43899cddda"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
