name = "Beyond the Singularity"
author = "ZotyDev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2000f52582c388c47ba72b3595ca623a9b5ef421966ad583ca7c86672a326ff"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
